"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.api
import cloudinary.uploader
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-^g^zilu&l2-u@pta!+lwv04pi@ct1dc+fqxpy@#t1$pv(-ys3%'

DEBUG = True

ALLOWED_HOSTS = ['*']  # Render handles this


# ---------------------
# INSTALLED APPS
# ---------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'new_app',
    'products',

    # Cloudinary
    'cloudinary',
    'cloudinary_storage',

    # CORS
    'corsheaders',
]


# ---------------------
# MIDDLEWARE
# ---------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',      # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# ---------------------
# DATABASE (MySQL)
# ---------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# ---------------------
# CLOUDINARY CONFIG
# ---------------------
cloudinary.config(
    cloud_name=os.getenv('CLOUD_NAME'),
    api_key=os.getenv('CLOUD_API_KEY'),
    api_secret=os.getenv('CLOUD_API_SECRET')
)


# ---------------------
# PASSWORD VALIDATION
# ---------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------
# INTERNATIONALIZATION
# ---------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------
# STATIC FILES
# ---------------------
STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
#               🔥 FINAL CORS SETTINGS (WORKING)
# ============================================================

# Allow all origins (required for Render proxy)
CORS_ALLOW_ALL_ORIGINS = True

# Allow cookies (important)
CORS_ALLOW_CREDENTIALS = True

# Allow JSON & all custom headers
CORS_ALLOW_HEADERS = ["*"]

# Allow all methods (POST, GET, OPTIONS)
CORS_ALLOW_METHODS = ["*"]


# ============================================================
#               🔥 CSRF SETTINGS (COMPULSORY)
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://own-prac1-1.onrender.com",
    "https://*.netlify.app",
    "https://*.vercel.app",
]

# Development only
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

